export { default as H3 } from "./H3";
export { default as HeaderLink } from "./HeaderLink";
export { default as HeaderButton } from "./HeaderButton";
export { default as FooterH4 } from "./FooterH4";
export { default as FooterSpan } from "./FooterSpan";
export { default as FooterLink } from "./FooterLink";
export { default as FooterSocialLink } from "./FooterSocialLink";
export { default as Benefit } from "./Benefit";
export { default as HomeProduct } from "./HomeProduct";
